#pragma once
#include "s21_list.h"
#include "s21_vector.h"
#include "s21_array.h"
#include "s21_stack.h"
#include "s21_queue.h"
#include "s21_set.h"
#include "s21_map.h"
#include "s21_multiset.h"
